# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui
from PyQt5 import QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 333)
        MainWindow.setMinimumSize(QtCore.QSize(701, 333))
        MainWindow.setMaximumSize(QtCore.QSize(701, 333))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/usr/share/icons/hicolor/scalable/apps/brightness-controller.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 511, 261))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 231, 211))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.primary_brightness = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.primary_brightness.setProperty("value", 99)
        self.primary_brightness.setOrientation(QtCore.Qt.Vertical)
        self.primary_brightness.setObjectName("primary_brightness")
        self.horizontalLayout_2.addWidget(self.primary_brightness)
        self.primary_red = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.primary_red.setProperty("value", 99)
        self.primary_red.setOrientation(QtCore.Qt.Vertical)
        self.primary_red.setObjectName("primary_red")
        self.horizontalLayout_2.addWidget(self.primary_red)
        self.primary_green = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.primary_green.setProperty("value", 99)
        self.primary_green.setOrientation(QtCore.Qt.Vertical)
        self.primary_green.setObjectName("primary_green")
        self.horizontalLayout_2.addWidget(self.primary_green)
        self.primary_blue = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.primary_blue.setProperty("value", 99)
        self.primary_blue.setOrientation(QtCore.Qt.Vertical)
        self.primary_blue.setObjectName("primary_blue")
        self.horizontalLayout_2.addWidget(self.primary_blue)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 40, 231, 211))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.secondary_brightness = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        self.secondary_brightness.setProperty("value", 99)
        self.secondary_brightness.setOrientation(QtCore.Qt.Vertical)
        self.secondary_brightness.setObjectName("secondary_brightness")
        self.horizontalLayout_3.addWidget(self.secondary_brightness)
        self.secondary_red = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        self.secondary_red.setProperty("value", 99)
        self.secondary_red.setOrientation(QtCore.Qt.Vertical)
        self.secondary_red.setObjectName("secondary_red")
        self.horizontalLayout_3.addWidget(self.secondary_red)
        self.secondary_green = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        self.secondary_green.setProperty("value", 99)
        self.secondary_green.setOrientation(QtCore.Qt.Vertical)
        self.secondary_green.setObjectName("secondary_green")
        self.horizontalLayout_3.addWidget(self.secondary_green)
        self.secondary_blue = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        self.secondary_blue.setProperty("value", 99)
        self.secondary_blue.setOrientation(QtCore.Qt.Vertical)
        self.secondary_blue.setObjectName("secondary_blue")
        self.horizontalLayout_3.addWidget(self.secondary_blue)
        self.horizontalLayout.addWidget(self.groupBox)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 260, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(100, 260, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(150, 260, 21, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(200, 260, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(290, 260, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(370, 260, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(420, 260, 21, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(470, 260, 16, 16))
        self.label_8.setObjectName("label_8")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(529, 0, 213, 204))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.primary_combobox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primary_combobox.sizePolicy().hasHeightForWidth())
        self.primary_combobox.setSizePolicy(sizePolicy)
        self.primary_combobox.setMaximumSize(QtCore.QSize(150, 28))
        self.primary_combobox.setObjectName("primary_combobox")
        self.verticalLayout.addWidget(self.primary_combobox)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.secondary_combo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.secondary_combo.setMaximumSize(QtCore.QSize(150, 28))
        self.secondary_combo.setObjectName("secondary_combo")
        self.verticalLayout.addWidget(self.secondary_combo)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setMaximumSize(QtCore.QSize(150, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 701, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionCheck_for_update = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_update.setEnabled(False)
        self.actionCheck_for_update.setObjectName("actionCheck_for_update")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionLicense)
        self.menuHelp.addAction(self.actionCheck_for_update)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Brightness Controller", None))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Primary", None))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Secondary", None))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Brightness", None))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", " R", None))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", " G", None))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", " B", None))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Brightness", None))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", " R", None))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", " G", None))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", " B", None))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Advanced", None))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Primary Brightness", None))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Secondary Brightness", None))
        self.secondary_combo.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>You can select the source of Secondary Brightness Here.</p></body></html>", None))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Color Temperature", None))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Default", None))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1900K Candle", None))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2600K 40W Tungsten", None))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "2850K 100W Tungsten", None))
        self.comboBox.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "3200K Halogen", None))
        self.comboBox.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5200K Carbon Arc", None))
        self.comboBox.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "5400K High Noon", None))
        self.comboBox.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "6000K Direct Sun", None))
        self.comboBox.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "7000K Overcast Sky", None))
        self.comboBox.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "20000K Clear Blue Sky", None))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Help", None))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "E&xit", None))
        self.actionHelp.setText(QtWidgets.QApplication.translate("MainWindow", "&Help", None))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "&About", None))
        self.actionLicense.setText(QtWidgets.QApplication.translate("MainWindow", "&License", None))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "&Save current settings", None))
        self.actionLoad.setText(QtWidgets.QApplication.translate("MainWindow", "&Load settings", None))
        self.actionCheck_for_update.setText(QtWidgets.QApplication.translate("MainWindow", "&Check for Update", None))

